"""add_d365_sync_states

Revision ID: a1f2c3d4e5f6
Revises: 4957b58d0c65
Create Date: 2026-09-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1f2c3d4e5f6'
down_revision: Union[str, None] = '4957b58d0c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d365_sync_states',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=False),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('records_synced_last_run', sa.Integer(), nullable=False),
    sa.Column('records_synced_total', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'entity_name', name='uq_d365_sync_kb_entity')
    )
    op.create_index(op.f('ix_d365_sync_states_knowledge_base_id'), 'd365_sync_states', ['knowledge_base_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_d365_sync_states_knowledge_base_id'), table_name='d365_sync_states')
    op.drop_table('d365_sync_states')
    # ### end Alembic commands ###
