"""add_d365_action_logs

Revision ID: b2c3d4e5f6a7
Revises: a1f2c3d4e5f6
Create Date: 2026-09-14 05:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'a1f2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

d365_action_status = sa.Enum(
    'pending_confirmation', 'executed', 'failed', 'cancelled',
    name='d365actionstatus',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    d365_action_status.create(op.get_bind(), checkfirst=True)
    op.create_table('d365_action_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('action_name', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', d365_action_status, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_d365_action_logs_user_id'), 'd365_action_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_d365_action_logs_knowledge_base_id'), 'd365_action_logs', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_d365_action_logs_action_name'), 'd365_action_logs', ['action_name'], unique=False)
    op.create_index(op.f('ix_d365_action_logs_status'), 'd365_action_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_d365_action_logs_status'), table_name='d365_action_logs')
    op.drop_index(op.f('ix_d365_action_logs_action_name'), table_name='d365_action_logs')
    op.drop_index(op.f('ix_d365_action_logs_knowledge_base_id'), table_name='d365_action_logs')
    op.drop_index(op.f('ix_d365_action_logs_user_id'), table_name='d365_action_logs')
    op.drop_table('d365_action_logs')
    d365_action_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
